### ISSUE TITLE
Readme has wrong port for plugin url

### ISSUE THREAD

**Issue by ccjoshk** [roemhildtg/vscode-arcgis-assistant#22]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
documentation bug

* **What is the current behavior?**
Documentation says that the plugin url is http://lvh.me:3030 but it appears to be http://lvh.me:3000. 

* **What is the expected behavior?**

Readme documentation says
> Go to the application settings page and register the URL for the VSCode assistant plugin (http://lvh.me:3000)

**Comment by roemhildtg** [comment]
Good call - I'll fix that in the readme.
